version: '2'
services:
    tillashowcase2-app:
        image: tillashowcase2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tillashowcase2-postgresql:5432/tillashowcase2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tillashowcase2-postgresql:
        extends:
            file: postgresql.yml
            service: tillashowcase2-postgresql
